useflags="x11-wm/openbox www-client/firefox app-emulation/wine-vanilla x11-drivers/xf86-video-amdgpu 
games-util/steam-meta sys-kernel/linux-firmware dev-vcs/git sci-mathematics/octave x11-misc/dunst 
x11-misc/polybar x11-misc/dmenu x11-misc/sddm app-editors/vim net-libs/nodejs net-wireless/gnuradio
net-analyzer/wireshark net-misc/icaclient app-emulation/virtualbox app-office/libreoffice dev-libs/glib:2 
dev-libs/libgcrypt dev-libs/nspr dev-libs/nss gnome-base/gconf gnome-extra/zenity media-libs/alsa-lib
media-libs/fontconfig media-libs/freetype:2 media-libs/libjpeg-turbo media-libs/libogg media-libs/libpng-compat:1.2
media-libs/libsdl media-libs/libtheora media-libs/libvorbis media-libs/openal net-misc/curl net-print/cups
sys-apps/dbus virtual/libusb:1 virtual/opengl x11-libs/cairo x11-libs/gdk-pixbuf x11-libs/gtk+:2 x11-libs/libX11
x11-libs/libXScrnSaver x11-libs/libXext x11-libs/libXfixes x11-libs/libXi x11-libs/libXrandr
x11-libs/libXrender x11-libs/pango x11-libs/pixman dev-util/systemtap"
actual_flags="X alisp alt-svc analog androiddump asm audio base bcg729 blksha1 brotli cacert capi capinfos captype cgi channels ciscodump clang coinmp crypt cscope ctrlport curl custom-cflags dftest digital dos dpauxmon dtrace dtv dumpcap dunstify editcap elogind eme-free faudio fec filter ftp gecko geckodriver gles2-only glib glpk gmp-autoupdate gnutls googledrive gopher gpg grc gssapi gstreamer headless highlight hsts http2 hwaccel i3wm ilbc imap initramfs inspector ipc ipv6 joystick ldap libvirt libxml2 loongson2f lprng-compat lto lvm mariadb maxminddb mbedtls mediawiki mediawiki-experimental mergecap mingw minizip modtool mono mpd netapi netlink network nghttp3 npm nss o-flag-munging odk opencl opengl openh264 openssl osmesa pax-kernel pcap pcre-jit pdfimport perforce performance-counters perl pgo plugin-ifdemo plugins pop3 ppcsha1 prelink progress-meter qhull qrupdate quiche racket randpkt randpktdump realtime redistributable reordercap rtmp run-exes samba savedconfig sbc screencast sdjournal sdk sdl session sharkd smi smtp snapshot sndio sound spandsp sparse ssh sshdump ssl sslv3 subversion sundials sysprof system-av1 system-harfbuzz system-icu system-jpeg system-libevent system-libvpx system-ssl system-webp systemd systemtap telnet terminal text2pcap tfshark tftp thread-safety tk trellis tshark tslib udev udpdump uhd unknown-license unwind usb user-session utils valgrind vboxwebsrv video vim-pager vkd3d vocoder vulkan wavelet webdav winssl xdg zeromq zstd"
