name: run-tests

on: [push, pull_request]

jobs:
    RunAllTests:
      runs-on: ubuntu-latest
      container: gentoo/stage3
      steps:
        - uses: actions/checkout@v2
        - name: run-tests
          run: bash install2.sh
