name: run-tests

on: [push]

jobs:
    JobOne:
        runs-on: ubuntu-latest
        container: gentoo/stage3:latest
        steps:
            -   uses: actions/checkout@v2
            -   name: run-tests
                run: bash src/install2.sh
